Initial commit of IPv6 Support for CNDP
CloudNativeDataPlane/cndp pull request #286
Opened 2023-04-23 16:27 UTC by mnjdhl

Initial code changes of IPv6 Support for CNDP

2023-04-23 18:51 UTC, KeithWiles commented
I briefly looked at the diffs and notices a few formatting problem. Tabstop needs to be set to 4 and insert spaces for a tab.

Look at the CONTRIBUTING.md file and install the per-commit hook, which also requires clang-format to be installed. You will most likely have to edit the files and reformat replacing tabs with 4 spaces. A number of tools and editors will do this for you i.e,. vim, vscode, ....

I also make sure all of the new files have the correct SPDX license must be BSD-3-Clause. Also make sure the copyright dates reflect the correct year(s).

Plus so please add a 'Signed-off-by: Your Name <email-address>' to the commits.

The changes are looking very good!

2023-04-24 06:43 UTC, mnjdhl commented
Thanks Keith for the feedback.
Will be following these guidelines.

2023-04-26 19:14 UTC, mnjdhl commented
@KeithWiles 
The changes (formatting, copyright and some cleanup) are still underway.
Will be pushing them in a day or two.

2023-04-27 06:49 UTC, mnjdhl commented
@KeithWiles 
Done the required changes. 
This commits contains:
- IPv6 protocol stack
- route for IPv6
- netif changes for IPv6

And still to come:
- NDP protocol and ICMP6 (minimum required)
- Integration of IPv6 with layer 2, layer 4 and FIB/RIB
- If anything more needed for IPv6 to work

Thanks for your support

2023-04-29 14:45 UTC, KeithWiles commented
Please have a look at the CONTRIBUTING.md file it has some suggestion to add pre-commit hook and/or running clang-format on the code. If you have not already added the clang-format git hook.

2023-05-02 15:37 UTC, mnjdhl commented
> Please have a look at the CONTRIBUTING.md file it has some suggestions like adding pre-commit hook and/or running clang-format on the code. If you have not already added the clang-format git hook.
Before pushing the commit 'git clang-format' was run. Apologize if you still see any formatting errors.

2023-05-02 16:00 UTC, KeithWiles commented
Thank you. I was making sure it was run, but will look at the code when you are ready. If ready for a review please let me know.

2023-05-03 16:29 UTC, mnjdhl commented
> Thank you. I was making sure it was run as the clang-format test was failing, but will look at the code when you are ready. If ready for a review please let me know.

Well, ipv6 functionality wise is not ready yet fully. This is work in progress. The integration with other layers is in progress and next will be  NDP/ICMP6. Likewise when all the dots are connected then only we can test the ipv6 functionality. 

So you can take a call whether to start review now or later when everything is ready.

2023-05-03 16:43 UTC, KeithWiles commented
I can convert the PR to a draft (or you can) and then convert it back when ready. I would think we can wait until it is complete, but I will take a quick look at the code and provide some high level comments.

2023-05-16 11:56 UTC, mnjdhl commented
> I can convert the PR to a draft (or you can) and then convert it back when ready. I would think we can wait until it is complete, but I will take a quick look at the code and provide some high level comments.

Have you looked at it?

2023-05-19 17:22 UTC, mnjdhl commented
Thanks a lot Keith! 
Will start addressing the comments mostly after completing other parts.

2023-05-27 15:57 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.h
> +
Done

2023-05-27 15:57 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.h
> +static uint32_t get_new_srhash();
It is used in ip6_output.c as well

2023-05-27 15:58 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.h
> +int get_sysctl_value(const char *path);
Done

2023-05-27 15:58 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.h
> +    union flowi_uli uli;
Removed it

2023-05-27 15:58 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.h
> +static inline uint32_t ip6_make_flowlabel(struct net *net, struct sk_buff *skb, uint32_t flowlabel,
Done it

2023-05-27 15:58 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.h
> +int get_sysctl_value(const char *path);
Done

And do you think we should move get_sysctl_value() to more generic source file?

2023-07-12 17:55 UTC, ekosi09 commented
Hello @KeithWiles 

To address your comments and queries about the code, @mnjdhl and I have made some changes and cleanups, so I would like to kindly ask you to review the PR again. 

It's rebased on top of the `main` CNDP project branch and has been evaluated by `clang-format` to follow the `CONTRIBUTING.md` guidelines.

Please let us know if there's any discrepancies or room for improvement.

Thank you in advance,
Emil

2023-07-12 20:12 UTC, KeithWiles requested changes
Starting to look good. I only had time to do a quick review as too many files to review. Plus most of the comments are nit picks.

I was thinking we should add an option to meson_option.txt to enable/disable IPv6 support. This way we can commit this PR and not affect the current code base. By committing this PR we can have a smaller PR while continuing to improve or fix IPv6 support.
I was thinking disable IPv6 nodes, but allow the files to be compiled similar to the TCP code was done.

What do you think?

2023-07-12 20:12 UTC, KeithWiles commented on lib/cnet/route/cnet_route6.c
> +    /* TODO: add notify support */
Same as the above comment

2023-07-12 20:12 UTC, KeithWiles commented on usrtools/txgen/app/meson.build
> +	'tg_ipv6.c',
Can the file name be ipv6.c ?

2023-07-12 20:12 UTC, KeithWiles commented on usrtools/txgen/app/tg_ipv6.h
> +#ifndef _TXGEN_IPV6_H_
ipv6.h ??

2023-07-17 04:33 UTC, mnjdhl commented on usrtools/txgen/app/tg_ipv6.h
> +#ifndef _TXGEN_IPV6_H_
Done

2023-07-17 04:42 UTC, mnjdhl commented on lib/cnet/chnl/cnet_chnl.c
> +            else if (ch->ch_proto->proto == IPPROTO_ICMPV6)
IPPROTO_ICMP  is not implemented yet, that's why check is not there.

2023-07-17 04:43 UTC, mnjdhl commented on lib/cnet/chnl/cnet_chnl.c
> +    if (ch->ch_proto->proto == IPPROTO_ICMPV6) {
IPPROTO_ICMP is not implemented yet, that's why check is not there.

2023-07-17 04:44 UTC, mnjdhl commented on lib/cnet/incs/cnet_fib_info.h
> + * Do a build lookup in the FIB table and return the objects
Done

2023-07-17 04:46 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.h
> +#if 0
Done

2023-07-17 04:47 UTC, mnjdhl commented on lib/cnet/nd6/cnet_nd6.c
> +        if (mac) {
Done

2023-07-17 04:48 UTC, mnjdhl commented on lib/cnet/nd6/cnet_nd6.c
> +        if (mac) {
Done

2023-07-17 04:48 UTC, mnjdhl commented on lib/cnet/nd6/cnet_nd6.c
> +        if (mac) {
Done

2023-07-17 04:49 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    /* Note:- Not implemented yet */
Done

2023-07-17 04:49 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    /* Note:- Not implemented yet */
Done

2023-07-17 04:50 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    if (nif == NULL) {
Done

2023-07-17 04:50 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    if (nif == NULL) {
Done

2023-07-17 04:51 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    /* Note:- Not implemented yet */
Done

2023-07-17 04:54 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    (void)iip;
Done

2023-07-17 04:55 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    (void)iip;
Done

2023-07-17 04:56 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    if (inet6_is_unspec_addr((struct in6_addr *)&iip->ip6.src_addr)) {
Done

2023-07-17 04:57 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    /* Note:- Not implemented yet */
Done

2023-07-17 04:57 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    /* Note:- Not implemented yet */
Done

2023-07-17 04:58 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    /* Note:- Not implemented yet */
Done

2023-07-17 04:58 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    /* All ND6 initilizations */
Done

2023-07-17 04:59 UTC, mnjdhl commented on usrtools/txgen/app/meson.build
> +	'tg_ipv6.c',
Done

2023-07-17 05:00 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +    (void)iip;
Done

2023-07-17 05:05 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.c
> +    if (seed > 0) {
Done

2023-07-17 05:11 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.c
> +srhash_init0(void)
Done

2023-07-17 05:12 UTC, mnjdhl commented on lib/cnet/ipv6/ip6_flowlabel.c
> +    if (access(path, R_OK) != 0) {
Done

2023-07-18 05:03 UTC, mnjdhl commented on lib/cnet/icmp6/icmp6_output.c
> +    (void)pcb;
Removed it

2023-07-18 05:05 UTC, mnjdhl commented on lib/cnet/icmp6/icmp6_output.c
> +    nxt = ICMP6_OUTPUT_NEXT_IP6_OUTPUT;
Removed it

2023-07-18 05:10 UTC, mnjdhl commented on lib/cnet/route/cnet_route6.c
> +    /* TODO: add timer support */
Removed the comment and added debug msg

2023-07-18 05:11 UTC, mnjdhl commented on lib/cnet/route/cnet_route6.c
> +    /* TODO: add notify support */
Removed the comment and added debug msg

2023-07-18 05:27 UTC, mnjdhl commented on lib/cnet/nd6/nd6.h
> +CNDP_API void nd6_send_ns(struct cne_graph *graph, struct cne_node *node, struct in6_addr *src_addr,
Done

2023-07-18 05:29 UTC, mnjdhl commented on lib/cnet/ipv6/cnet_ipv6.h
> +/* TBD: structs for IPv6 Extension Headers need to be added if required*/
Removed the comment now. If any issue comes we will add the extension later.

2023-07-18 06:46 UTC, mnjdhl commented on lib/cnet/nd6/nd6.c
> +             * Note:- This is not implemented yet. To compensate this we send
I have left with a meaningful comment to fix this now.

2023-07-18 12:48 UTC, ekosi09 commented
Hello @KeithWiles 

We've cleaned up the code and @mnjdhl fixed the issues that you mentioned. Please look into these changes and give us feedback for further improvements.

Thank you in advance,
Emil

2023-07-18 16:41 UTC, KeithWiles reviewed
I did a quick review and it appears to be good. Thanks for making it optional to build.

Do you think we can merge this PR as is and then continue to debug IPv6 with new PRs?

2023-07-19 12:22 UTC, ekosi09 commented
Hello @KeithWiles 

Thank you for checking the changes. We would appreciate if you could point us in the right direction regarding the pre-commit hook issue since we do the `git clang-format --diff HEAD~1` and `git clang-format HEAD~1` manually to see and fix the formatting of the committed files and it's passing without errors. Only then we force-push the commit to the `feature-ipv6` branch.

In the `CONTRIBUTING.md` document, the hook and the manual `git clang-format` are described as the options for formatting along with the clang-format file `.clang-format` to use with ninja, however we don't do that option.

Also, I can see that there is already a `.git/hooks/pre-commit` hook located in the branch and it's executable:
```
$ ls -l .git/hooks/pre-commit*                                                                                                                  git:feature-ipv6
-rwxr-xr-x 1 ekosic ekosic  414 srp  19 13:14 .git/hooks/pre-commit
-rwxr-xr-x 1 ekosic ekosic 1643 srp  12 15:07 .git/hooks/pre-commit.sample
```

Thank you for your efforts,
Emil

2023-07-19 13:19 UTC, KeithWiles commented
It appears you do have the pre-commit file setup correctly and here is the pre-commit file I have.

The pre-commit file should be run before you are able to commit the files. It maybe you need to modify the file in the feature-ipv6 branch by adding a space or space out a '=' to not be correct then commit the file. This way we can see if clang-format is working via the pre-commit hook.

foo = 1;
bar               = 2; // This line should be fixed by clang-format and align the '='

```
#! /bin/bash

for filename in $(git diff --cached --name-only | grep '.*\.[c|h]$'); do
  clang-format -style=file -i $filename; git add $filename;
done

for filename in $(git diff --cached --name-only | grep '.*\.go$'); do
  gofmt -s -w $filename; git add $filename;
done

for filename in $(git diff --cached --name-only | grep '.*\.jsonc$'); do
  ./tools/check_json.py --schema ./tools/cndp.schema $filename
done
```

2023-07-19 14:42 UTC, ekosi09 commented
Hello @KeithWiles 

Thank you for the explanation. I have tested the pre-commit hook just as you described and **I can confirm that it worked** (it fixed the clang-format issues right at committing the change):

1. I've made the following change (random variables):
```diff
diff --git a/lib/cnet/route/cnet_route6.c b/lib/cnet/route/cnet_route6.c
index 5359b86..9b3ec78 100644
--- a/lib/cnet/route/cnet_route6.c
+++ b/lib/cnet/route/cnet_route6.c
@@ -26,6 +26,9 @@
     ((1UL << RT6_NEXT_INDEX_SHIFT) - 1) /* MAX routes (16M) leaving bit 24-31 a next node index */
 #define RT6_DEFAULT_NUM_TBL8S (1 << 8)  /* Default number of tbl8 entries */
 
+uint16_t _test_a = 3;
+uint16_t _test_b            = 4;
+
```

2. I performed the addition and committing:
```
$ git commit -a -s -m 'testing pre-commit hook'
```

3. Then, I checked the file to see if clang-format was run:
```c
$ grep -C3 'uint16_t _test' lib/cnet/route/cnet_route6.c                                                                                        git:feature-ipv6
    ((1UL << RT6_NEXT_INDEX_SHIFT) - 1) /* MAX routes (16M) leaving bit 24-31 a next node index */
#define RT6_DEFAULT_NUM_TBL8S (1 << 8)  /* Default number of tbl8 entries */

uint16_t _test_a = 3;
uint16_t _test_b = 4;

int
cnet_route6_insert(int netdev_idx, struct in6_addr *dst, struct in6_addr *netmask,
```

This concludes that the pre-commit hook works as intended. Additionally to this, I've tried to run the hook script manually, and it does the same effect as just adding and committing the change, so I hope this concludes your concerns regarding the pre-commit hook.

As per your merging comment, I would like to kindly ask you if you could test the work since we didn't encounter any issues with it and we can then merge this commit and work on any additional fixes and issues later on.

Thank you in advance,
Emil

2023-07-19 15:08 UTC, KeithWiles commented
I do not have time this week and I hope to have some time this weekend.

2023-07-24 14:15 UTC, KeithWiles commented
I was working on reviewing and building the code this weekend. I ran into a number of warns and I tried to remove them, but I ran into more things I felt needed to be adjusted.

These changes caused a number of defines and structures to change, which affected a number of files. One example is I removed cne_fib6_conf structure and used cne_fib_conf everyplace. Then I moved CNE_FIB6_* to be CNE_FIB_* defines by moving them into the enum structures. Then I find that CNE_FIB6_IPV6_ADDR_SIZE could use the already defined IPV6_ADDR_LEN define. These changes and clang-format updating a number of files create a large number of file changes.

I wanted to give you a heads up on these changes and wanted to make sure these changes are OK. I would like to commit these changes, but wanted to make sure I was not stepping on anyone's toes and I would like to have you review them first of course.

I was not able to test the code other then running it, but I do not have the background to test IPv6 today.

Please let me know your thoughts and suggestions on how to move forward.

2023-07-24 17:39 UTC, KeithWiles commented
I can try pushing my changes to the repo, if I have write permission.

2023-07-25 12:10 UTC, ekosi09 commented
Hello @KeithWiles 

You can try pushing your changes to the `feature-ipv6` branch on our side so we can review it.

Thank you,
Emil

2023-07-27 19:43 UTC, mnjdhl commented
Hi Keith,

We have gone through your changes and  all of them look fine.

Please suggest the next step.

Thanks,

Manoj

2023-07-28 12:52 UTC, KeithWiles commented
Hi Manoj,

I was thinking we could merge the code. This will allow you to start a new set of PR's to fix any bugs or add more features.
The current version of IPv6 is experimental and we need more testing time. Along with testing time it would be good to do some performance testing between IPv4 and IPv6.

Does that sound reasonable?

2023-07-28 13:06 UTC, KeithWiles approved these changes
Approving to allow more debugging and changes. The IPv6 is not enabled by default and is still in an experimental state.

2023-07-28 14:36 UTC, mnjdhl commented
> Hi Manoj,
> 
> I was thinking we could merge the code. This will allow you to start a new set of PR's to fix any bugs or add more features. The current version of IPv6 is experimental and we need more testing time. Along with testing time it would be good to do some performance testing between IPv4 and IPv6.
> 
> Does that sound reasonable?

Sure Keith. Yeh it sounds good. Will merge it today.
Thanks a lot

2023-07-28 14:40 UTC, KeithWiles commented
I am waiting on a response from another possible PR that will move a few directories around and break the repo up into more manageable repo's for distribution. If that is done before merging this PR, I will look into merging IPv6 into the new directory/repo structure.

2023-07-28 14:44 UTC, mnjdhl commented
Okay Keith, we can wait for that PR.

2023-07-29 12:17 UTC, merged

2023-07-29 12:41 UTC, mnjdhl commented
Thanks a ton Keith for merging the PR.
It's real pleasure to work with you.

Warm regards,

Manoj