Update ansible roles to support fedora
CloudNativeDataPlane/cndp pull request #296
Opened 2023-04-27 17:11 UTC by haoruan

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Update ansible to support fedora, libbpf and libxdp installation.

#### Which issue(s) this PR fixes:
Fixes #228 

#### Special notes for your reviewer:
Update libbpf to v1.0.0, libxdp to v1.3.1
Tested in Ubuntu 20.04, Fedora 35, Fedora 38

Signed-off-by: Hao Ruan [hao.ruan@intel.com](mailto:hao.ruan@intel.com)
Signed-off-by: Xiaotian Chen [xiaotian.chen@intel.com](mailto:xiaotian.chen@intel.com)

2023-04-27 20:35 UTC, KeithWiles commented
@maryamtahhan if you have the time can you review these changes for Fedora with ansible. If not it is OK, will try to figure it out.

2023-04-28 10:04 UTC, maryamtahhan commented
@KeithWiles I will review

2023-04-28 13:10 UTC, haoruan commented on ansible/README.md
> +apt-get should now work to install the packages needed to use ansible.
Thanks, updated

2023-04-29 14:14 UTC, KeithWiles requested changes
A few comments, but still reviewing the changes.

2023-04-29 14:14 UTC, KeithWiles commented on ansible/README.md
> +```bash
Looks like a number of the image format sections ``` bash not correct. Some of them were in the file before being updated. Can you please fix these too.

Each ``` section needs to have a language type and I think it must have a space before the language type.

 Each code section needs to be something like this ``` bash with a space.

2023-05-03 13:16 UTC, KeithWiles commented
In vscode I see a number of linting errors or warnings. The code seems to render OK, but I think they need to be fixed.

Missing blanks lines around a couple places some ``` blocks do not have a code type ‘``` bash’. I will fix them.

From: Maryam Tahhan ***@***.***>
Date: Wednesday, May 3, 2023 at 8:09 AM
To: CloudNativeDataPlane/cndp ***@***.***>
Cc: Wiles, Keith ***@***.***>, Mention ***@***.***>
Subject: Re: [CloudNativeDataPlane/cndp] Update ansible roles to support fedora (PR #296)

@maryamtahhan commented on this pull request.

________________________________

In ansible/README.md<https://github.com/CloudNativeDataPlane/cndp/pull/296#discussion_r1183664716>:

>  apt-get should now work to install the packages needed to use ansible.



-```

+```bash

@KeithWiles<https://github.com/KeithWiles> are you seeing some warnings? it renders correctly for me.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting
https://www.thecodebuzz.com/highlight-bash-shell-code-in-markdown-readme-md-wiki-files/

—
Reply to this email directly, view it on GitHub<https://github.com/CloudNativeDataPlane/cndp/pull/296#discussion_r1183664716>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUWTDRKW3T3FB5W2R5PUEE3XEJKHRANCNFSM6AAAAAAXOEZGAQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-05-04 05:47 UTC, haoruan commented on ansible/README.md
>  make
Updated

2023-05-04 15:22 UTC, KeithWiles commented on ansible/README.md
>  make
Does not look like this was converted to `make rebuild-install` and is still using make only command.

2023-05-04 15:41 UTC, KeithWiles commented on ansible/cndp-ansible/roles/setup_hugepages/defaults/main.yml
> +update_grub_cmd:
Copyright notice.

2023-05-05 08:30 UTC, haoruan commented on ansible/README.md
>  make
Sorry, it should be updated now

2023-05-05 08:31 UTC, haoruan commented on ansible/cndp-ansible/roles/install_libxdp/tasks/main.yml
> +# Copyright (c) 2020-2023 Intel Corporation
Correct it to 2023

2023-05-05 21:36 UTC, merged