Replace "unable to" with "failed to" in error message
CloudNativeDataPlane/cndp pull request #297
Opened 2023-04-28 03:08 UTC by haoruan

#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
The error message format is inconsistent throughout the codebase, with a mix of 'Unable to xxx' and 'Failed to xxxx' formats. Since the 'Failed to' format is more commonly used in the codebase, this PR replaces all instances of 'Unable to' with 'Failed to' to unify the error message string.

Also add the guideline for contributing.

#### Which issue(s) this PR fixes:
Fixes #256 

Signed-off-by: Hao Ruan <hao.ruan@intel.com>
Signed-off-by: Xiaotian Chen <xiaotian.chen@intel.com>

2023-04-28 13:06 UTC, haoruan commented on CONTRIBUTING.md
> +// CNE_ERR_GOTO(out, "Unable to init CNE\n");
The commented code is just the old code, here I use this code as an example.

2023-04-28 13:10 UTC, haoruan commented on CONTRIBUTING.md
> +Avoid using "Uable to xxxx", use "Failed to xxx" instead for logging failed function calls:
Thanks, updated

2023-04-28 13:25 UTC, KeithWiles commented on CONTRIBUTING.md
> +// CNE_ERR_GOTO(out, "Unable to init CNE\n");
Maybe we should show the example usage.
``` c
  CNE_ERR_GOTO(out, "Unable to init CNE\n");  // Do NOT use 'unable to' phase here

  CNE_ERR_GOTO(out, "Failed to init CNE\n");  // Use 'failed to' instead.
```

2023-04-29 13:54 UTC, KeithWiles commented
The clang-format failed `} * req;` should be `} *req;`

2023-05-03 13:24 UTC, KeithWiles commented on examples/cnet-quic/quic-cli.c
> +} * reqs;
Remove the space between '* reqs' to get clang-format to pass. This should have been fixed with the per-commit hook running clang-format.

2023-05-03 13:25 UTC, KeithWiles requested changes
A few minor requests for change.

2023-05-03 17:55 UTC, KeithWiles approved these changes
LGTM

2023-05-03 17:58 UTC, merged

2023-05-04 05:13 UTC, haoruan commented
Thanks for updating the PR @maryamtahhan