Issue:257 Fix Bulk lookup FIB for IPV4
CloudNativeDataPlane/cndp pull request #306
Opened 2023-04-29 07:58 UTC by vikasJain85

Issue: https://github.com/CloudNativeDataPlane/cndp/issues/257

2023-04-29 08:02 UTC, vikasJain85 commented
Issue: https://github.com/CloudNativeDataPlane/cndp/issues/257
Signed-off-by: Vikas Jain [vikas.jain@intel.com](mailto:vikas.jain@intel.com)

2023-04-29 08:02 UTC, vikasJain85 commented
retest

2023-04-29 13:39 UTC, KeithWiles commented
To help fix the DCO error, click on the `Details` link next to the DCO action to get some help with adding the Signed-Off-by line.

2023-04-29 13:45 UTC, KeithWiles requested changes
Some minor comments to style, but I will be reviewing this code more later.

2023-04-29 13:45 UTC, KeithWiles commented on examples/cndpfwd/main.c
> +    if (eaddr == NULL || tx_port == NULL || ip_addr) {
The coding style for CNDP does not allow for single line for, if, while, do, ... statements to have {} around the line.

The CONTRIBUTING.md file should help with coding style.

2023-05-02 14:54 UTC, jeffreybshaw requested changes

2023-05-08 21:20 UTC, KeithWiles commented on examples/cndpfwd/l3-fwd.c
> +    uint64_t *nexthop = malloc(n * sizeof(uint64_t));
The malloc() also has a memory leak as nexthop is not freed.

How about changing this to:

``` c
uint16_t nhop[MAX_BURST];
uint16_t *nexthop = &nhop[0];
```

2023-05-08 21:21 UTC, KeithWiles commented on examples/cndpfwd/main.c
> +    struct ether_addr *eaddr = malloc (n_pkts * sizeof(struct ether_addr));
Same here:

``` c
struct ether_addr ethaddr[MAX_BURST];
struct ether_addr *eaddr = &ethaddr[0];
```
```

2023-05-08 21:27 UTC, KeithWiles commented on examples/cndpfwd/main.c
> +    uint16_t *tx_port = malloc (n_pkts * sizeof(uint16_t));
``` c
uint16_t tport[n_pkts];
uint16_t *tx_port = &tport[0];
```

2023-05-08 21:28 UTC, KeithWiles commented on examples/cndpfwd/main.c
> +    uint32_t *ip_addr = malloc (n_pkts * sizeof(uint32_t));
``` c
uint32_t ipaddrs[n_pkts];
uint32_t *ip_addr = &ipaddrs[0];
```

2023-05-08 22:10 UTC, KeithWiles approved these changes

2023-05-08 22:20 UTC, merged