vec:make vec lists dynamic
CloudNativeDataPlane/cndp pull request #31
Opened 2022-05-02 22:01 UTC by KeithWiles

Make the vec lists more dynamic instead of static sizes. Part of this change
is because of the CNET/TCP update comming, but also makes the code simpler.

With this update the old vec_*_ptr routines are not required as the macros
detect the correct size and type of vector lists.

The number of files changed is fair size, but most of the changes are minor
renaming of macros.

Signed-off-by: Keith Wiles <keith.wiles@intel.com>

2022-05-03 17:50 UTC, jeffreybshaw requested changes
Please look at the minor doxygen param fix, and a testcne change so that it reports failure when a test fails.

2022-05-03 17:50 UTC, jeffreybshaw commented on test/testcne/vec_test.c
> +    tst_end(tst, TST_PASSED);
Should you mark the test passed even if it failed?

2022-05-03 17:50 UTC, jeffreybshaw commented on lib/include/cne_vec.h
> + * @param elem
param name is "nelem". also missing the "esize" param documentation

2022-05-03 18:31 UTC, KeithWiles commented on lib/cnet/chnl/cnet_chnl.c
> +    ch->ch_rcv.cb_vec = vec_alloc(ch->ch_rcv.cb_vec, CHNL_VEC_SIZE);
Now that vec code is dynamic and can grow we do not need to preallocate that many ahead of time.

2022-05-03 18:32 UTC, KeithWiles commented on lib/cnet/chnl/cnet_chnl.h
> +#define CHNL_VEC_SIZE 32
See above

2022-05-03 18:44 UTC, jeffreybshaw approved these changes

2022-05-04 18:02 UTC, KeithWiles commented
reverify

2022-05-04 18:02 UTC, merged