cnet: add send completion events
CloudNativeDataPlane/cndp pull request #386
Opened 2024-07-29 17:31 UTC by jalalmostafa

CNET now has an event to know if sending has been processed. 
Now, eth_tx is also linked to `chnl_callback`. I added 2 new callback types: `CHNL_UDP_SENT_TYPE` and `CHNL_TCP_SENT_TYPE`.

2024-07-29 20:10 UTC, KeithWiles requested changes
Everything looks really good, thanks for the work!

I had a couple minor comments and some fixes to be done.

2024-07-29 20:10 UTC, KeithWiles commented on lib/cnet/eth/eth_tx.c
> -    CNE_SET_USED(graph);
Did you have a reason to remove this line and add __cne_unused? Maybe some compiler issue.

2024-07-30 09:35 UTC, jalalmostafa commented
Thanks for the review, Keith!
I pushed the fixes.

2024-07-30 18:50 UTC, KeithWiles approved these changes

2024-07-30 18:54 UTC, merged