tcp:add tcp support to CNET
CloudNativeDataPlane/cndp pull request #62
Opened 2022-05-23 20:00 UTC by KeithWiles

Update and rework the TCP support for CNET using a set of graph nodes to
manage the TCP protocol. The TCP protocol support can be enabled via the
meson_options.txt file.

Testing the TCP protocol using wireguard and other applications i.e wireshark, socat, telnet, ...
to verify the protocol and data managment is correct.

In this change a few examples needed to be update to support TCP and the changes to
the channel APIs. One change to the channel API is when the application is called
back to process Rx packets is the callback does not pass mbufs back in the call.
The packets are now placed on a receive queue and a call to chnl_recv() needs to
be done to get packets.

Note:
TCP active opens are not test yet. This PR is for anyone wanting to understand the changes or would like to test the code.
It does take a bit of effort to test, so please ask any questions if you want to test the code.

**_Also this is one big PR and I will break this down into smaller PR's when I get closer to submitting the changes._** 

Signed-off-by: Keith Wiles <keith.wiles@intel.com>

2022-05-24 15:20 UTC, jeffreybshaw requested changes

2022-05-24 15:20 UTC, jeffreybshaw commented on lib/include/cne_vec.h
> +        if (_n) {                                       \
check `if (_n > 0)`

2022-05-24 15:35 UTC, KeithWiles commented on lib/include/cne_vec.h
> +        if (_n) {                                       \
updated.

2022-05-24 15:35 UTC, KeithWiles commented on lib/core/pktmbuf/pktmbuf.h
> +    uint32_t allocated;
Turns out that field is not used, so removed.

2022-06-14 18:39 UTC, KeithWiles commented
Going to close this PR and reopen it after it is broken up into PRs for non-TCP issue.

2022-06-14 18:39 UTC, closed without merging