testcne: update meson with metrics test
CloudNativeDataPlane/cndp pull request #72
Opened 2022-06-02 20:10 UTC by sushmasi

Signed-off-by: Sushma Sitaram <sushma.sitaram@intel.com>

2022-06-02 20:42 UTC, jeffreybshaw commented
This is failing because we do not run the tests as root, which is required to open the uds socket used by the metrics library.
One thing we could try is to create a new group of tests, i.e. "sudo_test_names" that run with "sudo meson test -C builddir --suite su-short" where we run the tests that require sudo.

2022-06-03 15:26 UTC, KeithWiles approved these changes

2022-06-03 20:35 UTC, jeffreybshaw requested changes

2022-06-03 20:35 UTC, jeffreybshaw commented on test/testcne/meson.build
> +    'metrics',
Please do not do this. We don't run the meson tests as root, and this test willl fail if it is not run as root. See #75

2022-06-10 17:45 UTC, jeffreybshaw commented
@sushmasi - can you close this PR?

2022-06-10 17:49 UTC, closed without merging

2022-06-10 17:50 UTC, sushmasi commented
Changes taken care by commit 8770080db17e8df576b33622651b2ef985fef5f4